<?php

global $virtexOptions;

// do not edit this file
// all values are set via config settings or upon use

$virtexOptions['SSLcert'] = '';

$virtexOptions['SSLkey'] = '';

$virtexOptions['secret'] = '';

$virtexOptions['return_url'] = '';

$virtexOptions['shipping_required'] = '';     

?>