<?php

global $vxOptions;

// do not edit this file
// all values are set via config settings or upon use

$vxOptions['SSLcert'] = '';

$vxOptions['SSLkey'] = '';

$vxOptions['secret'] = '';

$vxOptions['notificationEmail'] = '';

$vxOptions['notificationURL'] = '';

$vxOptions['redirectURL'] = '';

$vxOptions['currency'] = '';

$vxOptions['physical'] = 'true';

$vxOptions['verifyPos'] = true;

?>